### ISSUE TITLE
Trivial:History: After restart from the crash, history back to default "January 1900"

### ISSUE THREAD

**Issue by schu37** [awestlund/GymGuide506#11]
• Summary: After restart from the crash, history back to default "January 1900."
	• Problem: After the app crashed, it restarts and the "History" jump to "January 1900" I believe that is some default.
	• Severity: trivial.
	• Suggestion: Add a button called "Today" to redirect date to today's date.

**Comment by awestlund** [comment]
Couldn't recreate the given issue. I would want to know how the app crashed in the first place.
