### ISSUE TITLE
Trivial:Scan QR code: After scanning the additional QR code in the file, adding them to workout is not quite convenient 

### ISSUE THREAD

**Issue by schu37** [awestlund/GymGuide506#12]
• Summary:  File = https://docs.google.com/document/d/1Ptm2HQ0WxfgUE5foJNIeGoBRWm1TzUC3IQz8QNVe57g/edit After scanning the additional QR code in the file, open their detailed page to workout is not quite convenient 
	• Problem: After Scan "Barbell", "Pull-up Bar", both workouts show up. However, to see each of them in a detailed page to Samsung S5, I need to click the very button, where "name" is half cropped by the phone screen, which causes incomplete display.
	• Severity: trivial.
	• Suggestion: Adjust the background image so it is responsive to the size of the phone.

**Comment by schu37** [comment]
Also, I have added all 12 "Recommended Workouts" to today's plan. After scanning QR code and add the above two new workouts, the completed workout page now only has 2 out of the 12 "Recommended Workouts"

**Comment by awestlund** [comment]
I didn't do anything to fix this, but when I added multiple finished workouts the app loads them compounded in the History view, after the day is selected again. So I could not recreate the issue, but I have confirmed that master doesn't have this issue as of right now.

**Comment by awestlund** [comment]
Okay so if you rebuild/exit the app and come back the saved workouts of the day are gone after adding a new finished workout. I do not know how to fix this issue
