### ISSUE TITLE
Adding workouts not working as intended?

### ISSUE THREAD

**Issue by xunzhou** [awestlund/GymGuide506#5]
Although toaster prompts "Added to Current Workout", it's only visible after clicking "video" in workout details.

**Comment by schu37** [comment]
Add workout: After exiting the program, reopen and go to "history" does not show the "Workout Completed on this day"
	• Summary:  Samsung S5- After exiting the program, reopen and go to "history" does not show the "Workout Completed on this day"
	• Problem: Add "Dumbbell Bicep Curls", "Barbell Squat" to the workout. Go to "History", the "Workout Completed on this day" has these two records. Then close the app. Then open the app. Go to "History", the "Workout Completed on this day" is empty. After clicking another day and then click today, the two workouts appear "Workout Completed on this day"
	• Severity: trivial.
	• Suggestion: Refresh the database every time when open the app.

**Comment by schu37** [comment]
Also after switching from "History" to "Today", or from "History" to " Profile". Then switch back to "History," the "Workout Completed on this day" is null. Maybe consider refreshing the database when this event happens, or add a "Refresh" button on this page

**Comment by awestlund** [comment]
Since the workout history is in a Fragment, we cannot simply/easily reload the the page when a workout is finished or when an exercise is added. Tried reloading the fragment after button is clicked but it did nothing. I do not know if we'll be able to fix this functionality.

**Comment by meganquinlan** [comment]
I also looked into allowing the fragment to be refreshed and changing the order of the fragment reloading had no effect for me.  I'm closing out this issue.
