### ISSUE TITLE
Scanning QR code in "QR Code Guide" are interpreted but not redirected.

### ISSUE THREAD

**Issue by xunzhou** [awestlund/GymGuide506#6]
QR codes in Iteration 2 Procedure are working as expected. But QR codes in the QR Code Guide got recognized but not redirected to corresponding detail page.

**Comment by xunzhou** [comment]
"Smith Machine" specifically.

**Comment by schu37** [comment]
Scan QR Code: After scan some QR code, APP crashes on Samsung S5 when select either "add" or "Video"
	• Summary: After scan some QR code, APP crashes on Samsung S5 when select either "add" or "Video"
	• Problem: Scan QR Code: Specifically, after scan "Dumbbell Bicep Curls", "Dumbbell Bicep Curls", "Barbell Squat", APP crashes on Samsung S5 when select either "add" or "Video"
	• Severity: a blocker.
	• Suggestion: Test the code again on some old devices see if this happens.

**Comment by DaveNugent** [comment]
I believe the issue was that when copying from the firebase documents section the code is not correctly interpreted, when generating QR code for equipment it can be copied from the string section of the exercise equipmentID. For smith machine that is 0PTG3SbvaFVHfmRYx0Zm.

**Comment by DaveNugent** [comment]
actually it was something else, it is fixed now
