### ISSUE TITLE
finish workout not working as expected

### ISSUE THREAD

**Issue by xunzhou** [awestlund/GymGuide506#7]
Although completed workouts are cleared from today view, nothing is visible in History view.

**Comment by awestlund** [comment]
These workouts show up in history when you select the day, you have to reselect it if it's for today to see the update

**Comment by schu37** [comment]
Add workout: After exiting the program, reopen and "Completed Workouts" under "Today" is empty
	• Summary:  Samsung S5- After exiting the program, reopen and go to "Today", "Completed Workouts" is empty
	• Problem: Add "Dumbbell Bicep Curls", "Barbell Squat" to the workout. Go to "History", After exiting the program, reopen app and go to "Today", "Completed Workouts" is empty, which suppose to have "Dumbbell Bicep Curls" and "Barbell Squat"
	• Severity: trivial.
	• Suggestion: Refresh the database every time when open the app.

**Comment by xunzhou** [comment]
As awestlund suggested, reselecting today's date solve this issue temporarily.
