### ISSUE TITLE
Upload profile photo require relogin

### ISSUE THREAD

**Issue by xunzhou** [awestlund/GymGuide506#9]
After uploading new profile photo, logout then log back in is required to refresh profile pic.

**Comment by xunzhou** [comment]
• Problem: refresh is required.
• Severity: trivial.
• Suggestion: profile pic gets updated automatically once user return to "profile page" from "update page"

**Comment by awestlund** [comment]
Mine let me upload a photo from my virtual device without any issues, I didn't get logged out when I hit update profile after the photo was selected.

**Comment by awestlund** [comment]
My photo also refreshed right away with out me needing to do anything!
